version: "3.7"

services:
  service:
    build: service/.
    image: swarm-practise_service:1 # swarm
    networks: #swarm
      - behold
    ports:
      - "5000:5000"

  api:
    build: api/.
    image: swarm-practise_api:1
    networks:
      - behold
    environment:
      PORT: 80
      URI: http://service:5000/
    ports:
      - "4000:80"

networks: #swarm
  behold:
