apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiDeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: apiContainer
          image: swarm-practise_api
          ports:
            - containerPort: 80
            # - port: 4000
            #   targetPort: 80
          env:
            - name: PORT
              value: 80
