apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  # namespace: kiskutya
spec:
  # type defaults to ClusterIP
  # type: LoadBalancer
  selector:
    # calls pods, not deployments!
    app: my-service
  ports:
    - port: 8080 # listening on
      targetPort: 5000 # fwd to
