apiVersion: v1
kind: Service
metadata:
  name: clusterService
  # namespace: kiskutya
spec:
  # type defaults to ClusterIP
  # type: LoadBalancer
  selector:
    # calls pods, not deployments!
    app: myService
  ports:
    - port: 80
      targetPort: 5000
