apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  # namespace: kiskutya
spec:
  # type defaults to ClusterIP
  type: LoadBalancer
  selector:
    # calls pods, not deployments!
    app: my-api
  ports:
    - port: 8080 # listening on
      targetPort: 80 # fwd to
