apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceDeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: serviceContainer
          image: swarm-practise_service
          ports:
            - containerPort: 80
            # - port: 4000
            #   targetPort: 80
          env:
            - name: HELLO
              value: hello
