apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: api-container
          image: swarm-practise_api:1
          imagePullPolicy: Never # use local image registry
          ports:
            - containerPort: 80
            # - port: 4000
            #   targetPort: 80
          env:
            - name: PORT
              value: "80"
            - name: URI
              value: http://cluster-service:8080
