apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
        - name: service-container
          image: swarm-practise_service:1
          ports:
            - containerPort: 5000
            # - port: 4000
            #   targetPort: 80
          env:
            - name: NOPE
              value: no need one
